# Generated by Django 5.1 on 2025-11-19 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Construccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='factura_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='app_Construccion.cliente')),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='app_Construccion.empleado')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='app_Construccion.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('num_serie', models.CharField(max_length=100, unique=True)),
                ('fecha_adq', models.DateField()),
                ('horas_uso', models.IntegerField(default=0)),
                ('cantidad', models.IntegerField()),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinarias', to='app_Construccion.empleado')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='maquinarias',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='app_Construccion.maquinaria'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='materiales',
            field=models.ManyToManyField(blank=True, related_name='proyectos', to='app_Construccion.material'),
        ),
    ]
