# Generated by Django 5.1 on 2025-11-19 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Construccion', '0002_material_proyecto_factura_total_factura_maquinaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='factura_generada',
            field=models.BooleanField(default=False),
        ),
    ]
